'use client';
import { useState } from 'react';
import { sitePath } from '../../lib/site-path';

export default function ShopPage(){
  const [cart,setCart]=useState(0);
  const [cartTotal,setCartTotal]=useState(0);
  const [cartOpen,setCartOpen]=useState(false);
  const [pack,setPack]=useState(1);
  const [productImage,setProductImage]=useState(sitePath('/story-buko-ube.jpg'));
  const prices:Record<number,string>={1:'₱499',2:'₱949',3:'₱1,399'};
  const changeQuantity=(delta:number)=>{const next=Math.max(0,cart+delta);setCart(next);setCartTotal(next===0?0:Math.max(0,cartTotal+(delta*499)))};
  return <main className="shopPage">
    <div className="announcement cutoffNotice">Cut-off for next-day orders is 4 pm, please don&apos;t forget to add your pickup date and time before checkout <span>💚</span> <b>→</b></div>
    <nav className="shopNav"><a className="brand" href={sitePath('/')}><span className="brandMark">py</span><span>PASTRY<br/>KITCHEN</span></a><div className="navLinks shopNavLinks"><a href={sitePath('/')}>Home</a><a className="active" href={sitePath('/shop')}>Shop</a><a href="#bundles">Bundles (Save More)</a><a href="mailto:PYPastryKitchen@gmail.com?subject=Wholesale%20Inquiry">Shop Wholesale</a><a href={`${sitePath('/')}#faq`}>Quality &amp; Safety</a></div><button className="cart cartIcon" aria-label={`Open cart with ${cart} items`} onClick={()=>setCartOpen(true)}>🛒<span>{cart}</span></button></nav>
    {cartOpen&&<><button className="cartOverlay" aria-label="Close cart" onClick={()=>setCartOpen(false)}/><aside className="cartDrawer sampleCart" aria-label="Shopping cart"><div className="cartDrawerHead"><h2>Your cart</h2><button onClick={()=>setCartOpen(false)} aria-label="Close cart">×</button></div>{cart===0?<div className="emptyCart"><span>🛒</span><h3>Your cart is empty</h3><p>Add a fresh batch to see your order here.</p></div>:<><p className="shippingUnlocked">🎉 You&apos;ve unlocked <strong>FREE SHIPPING!</strong></p><div className="cartLabels"><span>PRODUCT</span><span>TOTAL</span></div><div className="cartLine detailedCartLine"><img src={sitePath('/story-buko-ube.jpg')} alt="Buko Ube Mini Pie"/><div><h3>Buko Ube Mini Pie</h3><p>₱499.00 each</p><p>Freshly baked · Selected bundle</p><div className="quantityControl"><button onClick={()=>changeQuantity(-1)} aria-label="Decrease quantity">−</button><span>{cart}</span><button onClick={()=>changeQuantity(1)} aria-label="Increase quantity">+</button></div></div><div className="lineTotal"><strong>₱{cartTotal.toLocaleString()}</strong><button onClick={()=>{setCart(0);setCartTotal(0)}} aria-label="Remove item">♲</button></div></div><div className="cartSummary"><p><span>Subtotal</span><strong>₱{cartTotal.toLocaleString()}</strong></p><small>Taxes and shipping calculated at checkout</small><button onClick={()=>{window.location.href=`${sitePath('/checkout')}?qty=${cart}&total=${cartTotal}`}}>CHECK OUT</button><div className="paymentBadges"><b>●●</b><b>VISA</b></div></div></>}</aside></>}
    <section className="shopProduct">
      <div className="productGallery"><div className="mainProductImage"><img src={productImage} alt="Purple Yam Buko Ube Mini Pie"/></div><div className="productThumbs" aria-label="Product photos">{[['/story-buko-ube.jpg','Buko Ube pie'],['/story-cashew.jpg','Cashew Panutsa pie'],['/story-banana.jpg','Banana Kalinag pie'],['/py-menu.jpg','Full pastry menu']].map(([src,label])=><button key={src} className={productImage===src?'active':''} onClick={()=>setProductImage(src)} aria-label={`View ${label}`}><img src={src} alt=""/></button>)}</div></div>
      <div className="productDetails"><p className="eyebrow">SIGNATURE MINI PIE</p><h1>Buko Ube<br/>Mini Pie</h1><p className="productStars">★★★★★ <span>Hand-baked daily in Manila</span></p><p className="productDescription">Tender young coconut layered with two varieties of purple yam, nipa starch, and a beautifully flaky golden crust.</p><a className="ingredientLink" href={`${sitePath('/')}#faq`}>Ingredients &amp; freshness info</a><fieldset className="packChooser" id="bundles"><legend>Choose your box:</legend><div className="packGrid">{[[sitePath('/story-buko-ube.jpg'),'Buko Ube pie'],[sitePath('/story-cashew.jpg'),'Cashew Panutsa pie'],[sitePath('/story-banana.jpg'),'Banana Kalinag pie'],[sitePath('/py-menu.jpg'),'Full pastry menu']].map(([src,label])=><button key={src} className={productImage===src?'active':''} onClick={()=>setProductImage(src)} aria-label={`View ${label}`}><img src={src} alt=""/></button>)}</div></fieldset><button className="productAdd" onClick={()=>{setCart(cart+pack);setCartTotal(cartTotal+({1:499,2:949,3:1399} as Record<number,number>)[pack]);setCartOpen(true)}}>ADD {pack} {pack===1?'BOX':'BOXES'} TO CART — {prices[pack]}</button><div className="productAssurance"><span>✓ Hand-baked daily</span><span>✓ Pickup scheduling</span><span>✓ Gift-ready</span></div><p className="contactLine">Order: 0966 235 1036 · PYPastryKitchen@gmail.com</p></div>
    </section>
  </main>
}
